### PR TITLE
Add home button

### PR DESCRIPTION
**Pull request by LeviBickel**
This is adding a home button to the address bar. This is currently showing multiple changes due to my other pending pull request. This would fix one of the many requests on Issue #23. 

Thank you in advance for looking.

### CODE REVIEW

**Comment by robinrodricks** [comment]
Hi, Just got around to looking at this. Why was this closed?

**Comment by LeviBickel** [comment]
@robinrodricks I closed this because I thought the project was dead. I have made other changes since opening this. I have reopened this one for you to look at.

**Comment by robinrodricks** [comment]
No the project is not dead.

**Comment by robinrodricks** [comment]
Thanks for this! I will update the repo and build/check and verify.

**Pull request merged**
