### PR TITLE
Update to .NET Framework 4.8.1

### PR DESCRIPTION
**Pull request by LandarXT**
You may need VS 17.3 to compile

### CODE REVIEW

**Comment by robinrodricks** [comment]
I'm just curious why do you file dozens of minor PRs? Are you trying to get some github award or something? Most of your PRs don't add any functionality to the code and just minor things like constantly updating the versions. I'm just curious...

**Comment by LandarXT** [comment]
I'm focusing currently on keeping everything up to date but I will add some new features soon

**Comment by robinrodricks** [comment]
Maybe better to upgrade straight to NET 6.

**Comment by LandarXT** [comment]
I'll start working on that then; it may be a lot of work though as Framework and Core/.NET are pretty different

**Comment by robinrodricks** [comment]
Cool thanks

**Pull request closed without merging**
